name: Kubeutil image

on:
  push:
    paths:
    - 'develop'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd ../build
        echo "${{ secrets.DOCKERPW }}" | docker login -u "jrpamid" --password-stdin
        docker image build -t jrpamid/kubeutils:v0.0.1 .
        docker push jrpamid/kubeutils:v0.0.1
